config/routes.rb
Agape::Application.routes.draw do
  resources :teachers

  resources :students

end

app/models/student.rb
class Student
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Versioning

  field :first_name    , :type => String
  field :middle_name   , :type => String
  field :last_name     , :type => String
  field :date_of_birth , :type => Date
  field :number        , :type => Integer

  validates_presence_of( :first_name, :last_name, :date_of_birth, :number )
  validates_numericality_of( :number )
end

app/models/teacher.rb
class Teacher
  include Mongoid::Document
  field :first_name, :type => String
  field :middle_name, :type => String
  field :last_name, :type => String
  field :number, :type => Integer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.xml
  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @students }
    end
  end

  # GET /students/1
  # GET /students/1.xml
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @student }
    end
  end

  # GET /students/new
  # GET /students/new.xml
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.xml
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        format.html { redirect_to(@student, :notice => 'Student was successfully created.') }
        format.xml  { render :xml => @student, :status => :created, :location => @student }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @student.errors, :status => :unprocessable_entity }
      end
    end
  end



  # PUT /students/1
  # PUT /students/1.xml
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to(@student, :notice => 'Student was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @student.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.xml
  def destroy
    @student = Student.find(params[:id])
    @student.destroy

    respond_to do |format|
      format.html { redirect_to(students_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  # GET /teachers
  # GET /teachers.xml
  def index
    @teachers = Teacher.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @teachers }
    end
  end

  # GET /teachers/1
  # GET /teachers/1.xml
  def show
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @teacher }
    end
  end

  # GET /teachers/new
  # GET /teachers/new.xml
  def new
    @teacher = Teacher.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @teacher }
    end
  end

  # GET /teachers/1/edit
  def edit
    @teacher = Teacher.find(params[:id])
  end

  # POST /teachers
  # POST /teachers.xml
  def create
    @teacher = Teacher.new(params[:teacher])

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to(@teacher, :notice => 'Teacher was successfully created.') }
        format.xml  { render :xml => @teacher, :status => :created, :location => @teacher }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @teacher.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /teachers/1
  # PUT /teachers/1.xml
  def update
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      if @teacher.update_attributes(params[:teacher])
        format.html { redirect_to(@teacher, :notice => 'Teacher was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @teacher.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.xml
  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to(teachers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agape</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.haml
= form_for @student do |f|
  -if @student.errors.any?
    #error_explanation
      %h2= "#{pluralize(@student.errors.count, "error")} prohibited this student from being saved:"
      %ul
        - @student.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :middle_name
    = f.text_field :middle_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :date_of_birth
    = f.date_select :date_of_birth
  .field
    = f.label :number
    = f.text_field :number
  .actions
    = f.submit 'Save'

app/views/students/edit.html.haml
%h1 Editing student

= render 'form'

= link_to 'Show', @student
\|
= link_to 'Back', students_path

app/views/students/index.html.haml
%h1 Listing students

%table
  %tr
    %th First name
    %th Middle name
    %th Last name
    %th Date of birth
    %th Number
    %th
    %th
    %th

  - @students.each do |student|
    %tr
      %td= student.first_name
      %td= student.middle_name
      %td= student.last_name
      %td= student.date_of_birth
      %td= student.number
      %td= link_to 'Show', student
      %td= link_to 'Edit', edit_student_path(student)
      %td= link_to 'Destroy', student, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Student', new_student_path

app/views/students/new.html.haml
%h1 New student

= render 'form'

= link_to 'Back', students_path

app/views/students/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @student.first_name
%p
  %b Middle name:
  = @student.middle_name
%p
  %b Last name:
  = @student.last_name
%p
  %b Date of birth:
  = @student.date_of_birth
%p
  %b Number:
  = @student.number

= link_to 'Edit', edit_student_path(@student)
\|
= link_to 'Back', students_path

app/views/teachers/_form.html.haml
= form_for @teacher do |f|
  -if @teacher.errors.any?
    #error_explanation
      %h2= "#{pluralize(@teacher.errors.count, "error")} prohibited this teacher from being saved:"
      %ul
        - @teacher.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :middle_name
    = f.text_field :middle_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .field
    = f.label :number
    = f.text_field :number
  .actions
    = f.submit 'Save'

app/views/teachers/edit.html.haml
%h1 Editing teacher

= render 'form'

= link_to 'Show', @teacher
\|
= link_to 'Back', teachers_path

app/views/teachers/index.html.haml
%h1 Listing teachers

%table
  %tr
    %th First name
    %th Middle name
    %th Last name
    %th Number
    %th
    %th
    %th

  - @teachers.each do |teacher|
    %tr
      %td= teacher.first_name
      %td= teacher.middle_name
      %td= teacher.last_name
      %td= teacher.number
      %td= link_to 'Show', teacher
      %td= link_to 'Edit', edit_teacher_path(teacher)
      %td= link_to 'Destroy', teacher, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Teacher', new_teacher_path

app/views/teachers/new.html.haml
%h1 New teacher

= render 'form'

= link_to 'Back', teachers_path

app/views/teachers/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @teacher.first_name
%p
  %b Middle name:
  = @teacher.middle_name
%p
  %b Last name:
  = @teacher.last_name
%p
  %b Number:
  = @teacher.number

= link_to 'Edit', edit_teacher_path(@teacher)
\|
= link_to 'Back', teachers_path